---
- name: Instalar y configurar Moodle
  hosts: all
  become: yes

  tasks:
    - name: Asegurar que los paquetes requeridos están instalados
      apt:
        name:
          - apache2
          - unzip
          - wget
        state: present

    - name: Habilitar el módulo de reescritura de Apache
      command: a2enmod rewrite
      notify: Reiniciar Apache

    - name: Eliminar instalación previa de Moodle
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/v4.3.1.zip
        - /var/www/html/*

    - name: Descargar el código fuente de Moodle
      get_url:
        url: https://github.com/moodle/moodle/archive/refs/tags/v4.3.1.zip
        dest: /tmp/v4.3.1.zip

    - name: Extraer el archivo de Moodle
      unarchive:
        src: /tmp/v4.3.1.zip
        dest: /tmp
        remote_src: yes

    - name: Mover archivos de Moodle a /var/www/html
      command: mv -T /tmp/moodle-4.3.1 /var/www/html

    - name: Establecer propiedad y permisos correctos para Moodle
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        mode: "0755"
        recurse: yes

    - name: Crear directorio de datos de Moodle
      file:
        path: /var/moodledata
        state: directory
        owner: www-data
        group: www-data
        mode: "0777"

    - name: Actualizar configuración de PHP
      replace:
        path: "{{ item }}"
        regexp: ";max_input_vars = 1000"
        replace: "max_input_vars = 5000"
      loop:
        - /etc/php/8.3/apache2/php.ini
        - /etc/php/8.3/cli/php.ini
      notify: Reiniciar Apache

    - name: Instalar Moodle
      command: >
        sudo -u www-data php /var/www/html/admin/cli/install.php
        --lang={{ moodle.MOODLE_LANG }}
        --wwwroot={{ moodle.MOODLE_WWWROOT }}
        --dataroot={{ moodle.MOODLE_DATAROOT }}
        --dbtype={{ moodle.MOODLE_DB_TYPE }}
        --dbhost={{ moodle.BACKEND_PRIVATE_IP }}
        --dbname={{ moodle.MOODLE_DB_NAME }}
        --dbuser={{ moodle.MOODLE_DB_USER }}
        --dbpass={{ moodle.MOODLE_DB_PASS }}
        --fullname="{{ moodle.MOODLE_FULLNAME }}"
        --shortname="{{ moodle.MOODLE_SHORTNAME }}"
        --summary="{{ moodle.MOODLE_SUMMARY }}"
        --adminuser={{ moodle.MOODLE_ADMIN_USER }}
        --adminpass={{ moodle.MOODLE_ADMIN_PASS }}
        --adminemail={{ moodle.MOODLE_ADMIN_EMAIL }}
        --non-interactive
        --agree-license

    - name: Configurar ajustes de Moodle
      lineinfile:
        path: /var/www/html/config.php
        insertafter: "$CFG->admin"
        line: |
          $CFG->reverseproxy=1;
          $CFG->sslproxy=1;
      notify: Reiniciar Apache

  handlers:
    - name: Reiniciar Apache
      service:
        name: apache2
        state: reloaded
