---
- name: Playbook para hacer el deploy de la aplicación web Wordpress
  hosts: frontend
  become: yes

  vars_files:
    - /home/ubuntu/Practica_03/vars/variables.yml

  tasks:
    - name: Elimina el archivo wp-cli.phar en el directorio temporal /tmp
      file:
        path: /tmp/wp-cli.phar
        state: absent

    - name: Descargar wp-cli.phar
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /tmp/wp-cli.phar
        mode: 0755

    - name: Mover wp-cli.phar a /usr/local/bin/wp
      command: mv /tmp/wp-cli.phar /usr/local/bin/wp

    - name: Descargar WordPress core
      shell: wp core download --locale=es_ES --path=/var/www/html --allow-root
      args:
        creates: /var/www/html/wp-settings.php

    - name: Eliminar el directorio de instalación
      file:
        path: /var/www/html/wp-config.php
        state: absent

    - name: Crear wp-config.php
      command: wp config create --dbname="{{ db.wordpress_db_name }}" --dbuser="{{ db.wordpress_db_user }}" --dbpass="{{ db.wordpress_db_password }}" --dbhost="{{ db.wordpress_db_host }}" --path=/var/www/html --allow-root


    - name: Instalar WordPress
      command: wp core install --url="{{ wordpress.certificate_domain }}" --title='"{{ wordpress.wordpress_title }}"' --admin_user="{{ wordpress.wordpress_admin_user }}" --admin_password="{{ wordpress.wordpress_admin_pass }}" --admin_email="{{ wordpress.wordpress_admin_email }}" --path=/var/www/html --allow-root


    - name: Copia el archivo .htaccess desde el directorio ../htaccess/ al directorio /var/www/html/.
      copy:
        src: /home/ubuntu/Practica_03/htaccess/.htaccess
        dest: /var/www/html
        mode: 0755

    - name: Instalar plugin para seguridad de WordPress.
      command: sudo wp plugin install wp-staging --activate --path=/var/www/html --allow-root

    - name: Instalar y activar el plugin "wps-hide-login"
      command: sudo wp plugin install wps-hide-login --activate --path=/var/www/html --allow-root
      args:
        chdir: /var/www/html
      become: yes 

    - name: Cambiar los nombres del Link.
      command: sudo wp option update whl_page "guille" --path=/var/www/html --allow-root

    - name: Establece la estructura de las PermaLinks de WordPress.
      command: sudo wp rewrite structure '/%postname%/' --path=/var/www/html --allow-root

    - name: Cambiar el propietario y el grupo del directorio /var/www/html
      file:
        path: /var/www/html/
        state: directory
        owner: www-data
        group: www-data
        recurse: yes
