---
- name: Instalar y configurar WordPress con WP-CLI
  hosts: frontend_unico
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Descargamos el WP-CLI
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: '0755'

    - name: Crear directorio de WordPress
      file:
        path: "{{ wordpress.directory }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Descargar WordPress
      command: wp core download --locale=es_ES --path={{ wordpress.directory }} --allow-root
      args:
        chdir: "{{ wordpress.directory }}"

    - name: Crear archivo de configuración wp-config.php
      command: >
        wp config create
        --dbname={{ wordpress.db_name }}
        --dbuser={{ wordpress.db_user }}
        --dbpass={{ wordpress.db_password }}
        --dbhost={{ wordpress.db_host }}
        --path={{ wordpress.directory }}
        --allow-root
      args:
        chdir: "{{ wordpress.directory }}"

    - name: Instalación de WordPress
      command: >
        wp core install
        --url={{ certbot.domain }}
        --title="{{ wordpress.title }}"
        --admin_user={{ wordpress.db_admin_user }}
        --admin_password={{ wordpress.db_admin_pass }}
        --admin_email={{ wordpress.db_admin_email }}
        --path={{ wordpress.directory }}
        --allow-root
      args:
        chdir: "{{ wordpress.directory }}"

    - name: Instalar y activar el tema Mindscape
      command: wp theme install mindscape --activate --path={{ wordpress.directory }} --allow-root
      args:
        chdir: "{{ wordpress.directory }}"

    - name: Instalar y activar el plugin WPS Hide Login
      command: wp plugin install wps-hide-login --activate --path={{ wordpress.directory }} --allow-root
      args:
        chdir: "{{ wordpress.directory }}"

    - name: Configurar la URL oculta del login
      command: wp option update whl_page "{{ wordpress.hide_login }}" --path={{ wordpress.directory }} --allow-root
      args:
        chdir: "{{ wordpress.directory }}"

    - name: Configurar enlaces permanentes
      command: wp rewrite structure '/%postname%/' --path={{ wordpress.directory }} --allow-root
      args:
        chdir: "{{ wordpress.directory }}"

    - name: Copiar archivo .htaccess
      copy:
        src: ../htaccess/.htaccess
        dest: "{{ wordpress.directory }}/.htaccess"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Configurar HTTPS en wp-config.php
      lineinfile:
        path: "{{ wordpress.directory }}/wp-config.php"
        insertafter: "COLLATE"
        line: "$_SERVER['HTTPS'] = 'on';"
        state: present

    - name: Establecer permisos finales en WordPress
      file:
        path: "{{ wordpress.directory }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

  


