---
- name: Playbook para el setup del loadbalancer
  hosts: loadbalancer
  become: yes

  vars_files:
  - ../vars/variables.yml

  tasks:
  - name: Actualizamos los repositorios
    apt:
      update_cache: yes

  - name: Instalamos nginx
    apt:
      name: nginx
      state: present
  
  - name: Deshabilitamos el virtual host por defecto
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Copiamos el loadbalancer en la pagina
    copy:
      src: ../templates/load-balancer.conf
      dest: /etc/nginx/sites-available/load-balancer.conf
      mode: '755'

  - name: Remplazamos la ip del frontend por la del mysql
    replace:
      path: /etc/nginx/sites-available/load-balancer.conf
      regexp: "IP_FRONTEND_1"
      replace: "{{ mysql.frontend1_private_ip }}"
    
  - name: Remplazamos la ip del frontend por la del mysql
    replace:
      path: /etc/nginx/sites-available/load-balancer.conf
      regexp: "IP_FRONTEND_2"
      replace: "{{ mysql.frontend2_private_ip }}"

  - name: Remplazamos la ip del frontend por la del mysql
    replace:
      path: /etc/nginx/sites-available/load-balancer.conf
      regexp: "LE_DOMAIN"
      replace: "{{ certbot.domain }}"

  - name:
    file:
      src: /etc/nginx/sites-available/load-balancer.conf
      dest: /etc/nginx/sites-enabled/load-balancer.conf
      state: link

  - name: Recargamos Nginx 
    systemd:
      name: nginx
      state: restarted