---
- name: Playbook para configurar HTTPS
  hosts: LoadBalancer
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Instalar snapd (si no está instalado)
      package:
        name: snapd
        state: present

    - name: Habilitar servicio snapd
      service:
        name: snapd
        state: started
        enabled: yes

    - name: Instalar el servidor web Nginx
      apt:
        name: nginx
        state: present
    
    - name: Desinstalar instalaciones previas de Certbot
      apt:
        name: certbot
        state: absent

    - name: Instalar Certbot con snap
      snap:
        name: certbot
        classic: yes
        state: present

    - name: Solicitar y configurar certificado SSL/TLS a Let's Encrypt con certbot
      command:
        certbot --nginx \
        -m {{ certbot.email }} \
        --agree-tos \
        --no-eff-email \
        --non-interactive \
        -d {{ certbot.domain }}