---
- name: Playbook para instalar NFS Server
  hosts: NFS
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    - name: Instalar el servidor NFS
      apt:
        name: nfs-kernel-server
        state: present

    - name: Creates directory
      ansible.builtin.file:
        path: /var/www/html
        state: directory

    - name: Modificamos los permisos del directorio /var/www/html
      file:
        path: /var/www/html
        owner: nobody
        group: nogroup
        recurse: yes
        mode: 0755
    
    - name: Copiamos el archivo de exports de NFS
      copy:
        src: ../nfs/exports
        dest: /etc/exports

    - name: Reemplazamos el valor de la plantilla de /etc/exports
      replace: 
        path: /etc/exports
        regexp: 'FRONTEND_NETWORK'
        replace: "{{ FRONTEND_NETWORK }}"

    - name: Reiniciamos el servicio de base de datos
      service:
        name: nfs-kernel-server
        state: restarted