---
- name: Playbook para instalar NFS Client
  hosts: frontend
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    - name: Instalar el cliente NFS
      apt:
        name: nfs-common
        state: present

    - name: Montar NFS
      mount:
        path: /var/www/html
        src: "{{ NFS_SERVER_IP }}:/var/www/html"
        fstype: nfs
        opts: defaults
        state: mounted
