---
- name: Playbook para configurar el LoadBalancer entre los 2 FrontEnd
  hosts: LoadBalancer
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    - name: Eliminar el enlace simb贸lico del virtualhost por defecto
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copiar el archivo de configuraci贸n de Nginx
      copy:
        src: ../templates/loadbalancer.conf
        dest: /etc/nginx/sites-available
        mode: 0755

    - name: Sustituir valores en la plantilla de configuraci贸n de Nginx
      replace:
        path: /etc/nginx/sites-available/loadbalancer.conf
        regexp: "IP_FRONTEND_1"
        replace: "{{ ip.frontend1 }}"

    - name: Sustituir valores en la plantilla de configuraci贸n de Nginx
      replace:
        path: /etc/nginx/sites-available/loadbalancer.conf
        regexp: "IP_FRONTEND_2"
        replace: "{{ ip.frontend2 }}"

    - name: Habilitar el virtualhost del balanceador de carga
      file:
        src: /etc/nginx/sites-available/loadbalancer.conf
        dest: /etc/nginx/sites-enabled/loadbalancer.conf
        state: link

    - name: Reiniciar el servidor web nginx
      service:
        name: nginx
        state: restarted